spring.datasource.url=jdbc:postgresql://localhost:5432/briefly
spring.datasource.username=postgres
spring.datasource.password=qwerty

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

openai.api.key=${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}
openai.model=gpt-4o-mini