spring.datasource.url=jdbc:postgresql://localhost:5432/briefly
spring.datasource.username=PG_KEY
spring.datasource.password=PG_PASS

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

openai.api.key=${OPENAI_API_KEY}
openai.model=gpt-4o-mini